# -*- coding: utf-8 -*-
"""Ayudantia 5 - funciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KaieHp7e0itmfcJ89cBSWXqRiFq7hCzU

utils.py
"""

def botar(objeto):
  if tamaño del objeto es grande:
    botar al frente de la casa
  elif tamaño del objeto es medio:
    abrir bolsa de basura nueva
    botar
  else:
    buscar bolsa abierta
    botar

def cosasConValor(objeto):
  buscar en internet el valor de (objeto)
  if valor alto or valor medio:
    guardar en monton de (paraVender)
  else:
    botar(objeto)

def cosasSentimentales(objeto):
  ver si es un real valor sentimental
  if True:
    guardar
  else:
    botar(objeto)

def donar(objeto):
  if objeto limpio y buen estado:
    donamos a caridad
  else:
    botar(objeto)

"""main.py"""

import utils

objetos = casaAbuela["lampara","reloj antiguo", "boleta de la primera cita con el primer amor", "titulo de 8vo basico del 2do hijo", "collar", "tabla de planchar rota a la mitad",
                     "cama de autito", "cuna", "macetero del rayo mcqueen", "caja con muchos clavos", "maquina de coser antigua rota", "parlante bluetooth", "ropa con hoyos", "ropa",
                     "calcetines", "vestido de 1970 de Copacabana"]

for objeto in objetos:
  if objeto == sentimental:
    utils.cosasSentimentales(objeto)
  elif objeto == Valor:
    utils.cosasConValor(objeto)
  elif objeto == para donar:
    utils.donar(objeto)
  else:
    utils.botar(objeto)
  objetos -= objeto

from utils import cosasSentimentales, cosasConValor, botar

objetos = casaAbuela["lampara","reloj antiguo", "boleta de la primera cita con el primer amor", "titulo de 8vo basico del 2do hijo", "collar", "tabla de planchar rota a la mitad",
                     "cama de autito", "cuna", "macetero del rayo mcqueen", "caja con muchos clavos", "maquina de coser antigua rota", "parlante bluetooth", "ropa con hoyos", "ropa",
                     "calcetines", "vestido de 1970 de Copacabana"]

for objeto in objetos:
  if objeto == sentimental:
    cosasSentimentales(objeto)
  elif objeto == Valor:
    cosasConValor(objeto)
  else:
    botar(objeto)
  objetos -= objeto