# -*- coding: utf-8 -*-
"""Ayudantia 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lguI4DVmiEM6NBPxrDpGUApj37I7nhps

Construye un programa en Python que le pida al usuario 3 números enteros y los muestre en pantalla de mayor a menor. (Usar If Anidados)
"""

a = int(input())
b = int(input())
c = int(input())

if a > b:
  if a > c:
    if b > c:    # A mayor
      print(f"{a},{b},{c}") # a > b > c
    else:
      print(f"{a},{c},{b}") # a > c > b
  else:         # C mayor
    print(f"{c},{a},{b}") # c > a > b
else:
  if a > c:   # B mayor
    print(f"{b},{a},{c}") # b > a > c
  else:    # A menor
    if c > b:
      print(f"{c},{b},{a}") # c > b > a
    else:
      print(f"{b},{c},{a}") # b > c > a

"""Construye un programa en Python que le pida al usuario un número entero y diga si es primo o compuesto (no primo). Numeros del 1 al 20."""

resto = 1

while resto != 0:
  a = int(input())
  while a < 21:
    if (a > 3):  # 4 al 20
      resto = a % 2
      if resto == 0:
        print("No es numero primo")
        break
      else:
        resto = a % 3
        if resto == 0:
          print("No es numero primo")
        else:
          print("Numero primo")
        break
    elif a > 0:   # 1, 2, 3
      print("Numero primo")
    else:   # todo el resto
      print("No es un numero del 1 al 20")
  if a > 20:
    print("No es un numero del 1 al 20")